FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY ../cloud .
RUN go build -o /app/netprowl-cloud .

FROM alpine:latest
RUN apk add --no-cache ca-certificates
COPY --from=builder /app/netprowl-cloud /usr/local/bin/
EXPOSE 8080
CMD ["netprowl-cloud"]
