import { useState } from 'react';
import { PrintReport } from './PrintReport';

// pdfmake setup
const pdfMake = require('pdfmake/build/pdfmake');
const pdfFonts = require('pdfmake/build/vfs_fonts');
(pdfMake as any).vfs = (pdfFonts as any).pdfMake.vfs;

export interface PipelineResult {
  type: 'port' | 'service' | 'vuln' | 'fuzz' | 'tls';
  host?: string;
  ip?: string;
  port?: number;
  severity?: string;
  name?: string;
  template?: string;
  matched?: string;
  [key: string]: any;
}

export function ExportPanel({ results }: { results: PipelineResult[] }) {
  const vulns = results.filter(r => r.type === 'vuln' || r.type === 'tls');
  const ports = results.filter(r => r.type === 'port');

  const printExport = () => {
    window.print();
  };

  const pdfMakeExport = () => {
    const vulnRows = vulns.map((v: PipelineResult) => [
      v.severity?.toUpperCase() || 'N/A',
      v.template || v.name || 'Unknown',
      `${v.host || v.ip || 'N/A'}:${v.port || 'N/A'}`,
    ]);

    const docDefinition = {
      content: [
        { text: 'NetProwl Security Report', style: 'header' },
        { text: `Generated: ${new Date().toLocaleString()}`, style: 'subheader' },
        { text: `Total: ${results.length} | Ports: ${ports.length} | Vulns: ${vulns.length}`, style: 'subheader' },
        { text: ' ' },
        {
          table: {
            headerRows: 1,
            widths: ['auto', '*', 'auto'],
            body: [
              [{ text: 'Severity', bold: true }, { text: 'Finding', bold: true }, { text: 'Target', bold: true }],
              ...vulnRows,
            ],
          },
          layout: 'lightHorizontalLines',
        },
      ],
      styles: {
        header: { fontSize: 18, bold: true, margin: [0, 0, 0, 10] } as any,
        subheader: { fontSize: 11, margin: [0, 3, 0, 3] } as any,
      },
      defaultStyle: { fontSize: 10 } as any,
    };
    (pdfMake as any).createPdf(docDefinition).download(`netprowl-report-${Date.now()}.pdf`);
  };

  const jsonExport = () => {
    const blob = new Blob([JSON.stringify(results, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `netprowl-report-${Date.now()}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const htmlExport = () => {
    const html = `<!DOCTYPE html><html><head><title>NetProwl Report</title><style>body{font-family:system-ui;padding:40px}pre{white-space:pre-wrap}table{width:100%;border-collapse:collapse}th,td{border:1px solid #ddd;padding:8px;text-align:left}th{background:#f5f5f5}</style></head><body><h1>NetProwl Report</h1><p>Generated: ${new Date().toLocaleString()}</p><table><tr><th>Severity</th><th>Finding</th><th>Target</th></tr>${vulns.map((v: PipelineResult) => `<tr><td>${v.severity?.toUpperCase()}</td><td>${v.template || v.name}</td><td>${v.host || v.ip}:${v.port}</td></tr>`).join('')}</table><footer style="margin-top:40px;color:#999;font-size:12px">Generated by NetProwl v0.1.0</footer></body></html>`;
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `netprowl-report-${Date.now()}.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div>
      {results.length > 0 && <PrintReport results={results} />}
      <div className="flex gap-2 mt-4">
        <button onClick={printExport} className="text-sm bg-blue-100 text-blue-800 px-3 py-1 rounded hover:bg-blue-200">PDF (Quick)</button>
        <button onClick={pdfMakeExport} className="text-sm bg-green-100 text-green-800 px-3 py-1 rounded hover:bg-green-200">PDF (Formal)</button>
        <button onClick={jsonExport} className="text-sm bg-purple-100 text-purple-800 px-3 py-1 rounded hover:bg-purple-200">JSON</button>
        <button onClick={htmlExport} className="text-sm bg-orange-100 text-orange-800 px-3 py-1 rounded hover:bg-orange-200">HTML</button>
        <span className="text-xs text-gray-400 self-center ml-2">{results.length} results</span>
      </div>
    </div>
  );
}