interface PrintReportProps {
  results: any[];
}

export function PrintReport({ results }: PrintReportProps) {
  const vulns = results.filter((r: any) => r.type === 'vuln' || r.type === 'tls');
  const ports = results.filter((r: any) => r.type === 'port');

  return (
    <div className="print-report hidden">
      <style>{`
        @media print {
          .print-report { display: block !important; }
          body * { visibility: hidden; }
          .print-report, .print-report * { visibility: visible; }
          .print-report { position: fixed; left: 0; top: 0; width: 100%; }
          .print-report { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; }
          .print-report h1 { font-size: 24px; font-weight: 700; margin-bottom: 16px; }
          .print-report .section { margin-bottom: 20px; }
          .print-report .vuln-item { padding: 8px 0; border-bottom: 1px solid #eee; font-size: 13px; }
          .print-report .footer { margin-top: 40px; font-size: 11px; color: #999; }
        }
      `}</style>
      <div style={{ padding: '40px' }}>
        <h1 style={{ fontSize: '24px', fontWeight: 700, marginBottom: '16px' }}>NetProwl Security Report</h1>
        <div style={{ fontSize: '12px', color: '#666', marginBottom: '24px' }}>
          Generated: {new Date().toLocaleString()}
        </div>

        <div className="section">
          <div style={{ fontWeight: 600, marginBottom: '8px' }}>Summary</div>
          <div>Total: {results.length} findings</div>
          <div>Ports: {ports.length} | Vulnerabilities: {vulns.length}</div>
        </div>

        {vulns.length > 0 && (
          <div className="section">
            <div style={{ fontWeight: 600, marginBottom: '8px' }}>Vulnerabilities</div>
            {vulns.map((v: any, i: number) => (
              <div key={i} className="vuln-item">
                <span style={{ fontWeight: 600 }}>[{v.severity?.toUpperCase()}]</span>
                {' '}{v.template || v.name}
                <span style={{ color: '#888' }}> — {v.host || v.ip}:{v.port}</span>
              </div>
            ))}
          </div>
        )}

        <div className="footer">Generated by NetProwl v0.1.0</div>
      </div>
    </div>
  );
}